CS8795: Partial method 'RuntimeFeature.ThrowIfMultithreadingIsNotSupported()' must have an implementation part because it has accessibility modifiers.
vs
error CS0122: 'RuntimeFeature.ThrowIfMultithreadingIsNotSupported()' is inaccessible due to its protection level