[wasm] Fix regressed file sizes for blazor (#92664)
* [wasm] Add getter for __indirect_function_table

.. so that can work even if it gets renamed during minimization.

* [wasm] build: Revert to older behavior for WasmNativeStrip

The earlier change was done in 678fd6a73756f8438be115898cdd4fe0500e3d18,
which changed to pass `-g` to the link step also. But that resulted in
increased native file sizes.

Changed sizes for the `minimum blazor template - publish` scenario:

```
                                                          | Last rc1 run     | With the change
----------------------------------------------------------|----------------- |------------------
SOD - Minimum Blazor Template - Publish                   |8590723.000 bytes |7889806.000 bytes
Total Uncompressed _framework                             |4304274.000 bytes |4202273.000 bytes
pub/wwwroot/_framework/dotnet.js                          |35722.000 bytes   |35838.000 bytes
pub/wwwroot/_framework/dotnet.native.8.0.0-VERSION.js     |239307.000 bytes  |134566.000 bytes
pub/wwwroot/_framework/dotnet.native.wasm                 |1174394.000 bytes |1148841.000 bytes
pub/wwwroot/_framework/dotnet.runtime.8.0.0-VERSION.js    |221356.000 bytes  |221712.000 bytes
```

(cherry picked from commit ae93e81f4a5ff4a1596186f8719b0dccb5480f2c)

* [wasm] cleanup corresponding tests

(cherry picked from commit 0207d607336370b1981081992065e6f84c8b0d1a)

* [wasm] Remove WasmNativeStrip from wasm.proj as it will have no effect

(cherry picked from commit 91379ddfeec43839d310e3f2081d184626c1f916)

* disable non-wasm perf builds

* address feedback from Katelyn Gadd

* address review feedback

* remove debug bits

* Revert "address review feedback"

This reverts commit 68e954d4635d039857fcd1a6f20e978320dea7dd.

This caused tests to fail with:
```
fail: [out of order message from the browser]: http://127.0.0.1:36071/_framework/dotnet.runtime.js 2:12344 "MONO_WASM: onRuntimeInitializedAsync() failed" TypeError: t.getWasmIndirectFunctionTable is not a function
          at br (http://127.0.0.1:36071/_framework/dotnet.runtime.js:3:55253)
          at zr (http://127.0.0.1:36071/_framework/dotnet.runtime.js:3:60544)
          at http://127.0.0.1:36071/_framework/dotnet.runtime.js:3:214955
fail: [out of order message from the browser]: http://127.0.0.1:36071/_framework/dotnet.js 2:917 "MONO_WASM: TypeError: t.getWasmIndirectFunctionTable is not a function\n    at br (http://127.0.0.1:36071/_framework/dotnet.runtime.js:3:55253)\n    at zr (http://127.0.0.1:36071/_framework/dotnet.runtime.js:3:60544)\n    at http://127.0.0.1:36071/_framework/dotnet.runtime.js:3:214955"
```

* lifting emscripten internals

* Update src/mono/wasm/runtime/jiterpreter-support.ts

* Update src/mono/wasm/runtime/jiterpreter-support.ts

* track changes

* Fix build

* workload-testing.targets: fix shared framework install when dotnet-none is already installed

* import ENVIRONMENT_IS_NODE

* fix build

---------

Co-authored-by: pavelsavara <pavel.savara@gmail.com>
Co-authored-by: Larry Ewing <lewing@microsoft.com>