Fix roslyn analyzer issues
```
/__w/1/s/src/libraries/Common/src/System/Data/Common/MultipartIdentifier.cs(71,17): error CA2249: Use 'string.Contains' instead of 'string.IndexOf' to improve readability (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2249) [/__w/1/s/src/libraries/System.Data.Common/src/System.Data.Common.csproj]
/__w/1/s/src/libraries/Common/src/System/Data/Common/MultipartIdentifier.cs(71,55): error CA2249: Use 'string.Contains' instead of 'string.IndexOf' to improve readability (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2249) [/__w/1/s/src/libraries/System.Data.Common/src/System.Data.Common.csproj]
/__w/1/s/src/libraries/Common/src/System/Data/Common/MultipartIdentifier.cs(114,33): error CA2249: Use 'string.Contains' instead of 'string.IndexOf' to improve readability (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2249) [/__w/1/s/src/libraries/System.Data.Common/src/System.Data.Common.csproj]
/__w/1/s/src/libraries/Common/src/System/Data/Common/MultipartIdentifier.cs(136,33): error CA2249: Use 'string.Contains' instead of 'string.IndexOf' to improve readability (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2249) [/__w/1/s/src/libraries/System.Data.Common/src/System.Data.Common.csproj]
/__w/1/s/src/libraries/Common/src/System/Data/Common/MultipartIdentifier.cs(141,33): error CA2249: Use 'string.Contains' instead of 'string.IndexOf' to improve readability (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2249) [/__w/1/s/src/libraries/System.Data.Common/src/System.Data.Common.csproj]
/__w/1/s/src/libraries/System.Data.Common/src/System/Data/Common/DBCommandBuilder.cs(736,56): error CA2249: Use 'string.Contains' instead of 'string.IndexOf' to improve readability (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2249) [/__w/1/s/src/libraries/System.Data.Common/src/System.Data.Common.csproj]
/__w/1/s/src/libraries/System.Data.Common/src/System/Data/Common/DBCommandBuilder.cs(740,56): error CA2249: Use 'string.Contains' instead of 'string.IndexOf' to improve readability (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2249) [/__w/1/s/src/libraries/System.Data.Common/src/System.Data.Common.csproj]
```

Remaining:
`/__w/1/s/src/libraries/System.Data.Common/src/System/Data/Common/DbConnectionOptions.cs(168,26): error CA1862: Prefer using 'string.Equals(string, StringComparison)' to perform a case-insensitive comparison (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1862) [/__w/1/s/src/libraries/System.Data.Common/src/System.Data.Common.csproj]`