AggregateException: Use StringBuilder.AppendFormat (dotnet/coreclr#15747)
Use `AppendFormat(...)` instead of `Append(string.Format(...))` and
`AppendLine()` instead of `Append(Environment.NewLine)`.

Commit migrated from https://github.com/dotnet/coreclr/commit/41d23b05acac98c68d3b348c60bf151cfedd778f