Fix build error due to unused parameter in pal_console.c
```
src/native/libs/System.Native/pal_console.c(42,45): error G60964CEC: (NETCORE_ENGINEERING_TELEMETRY=Build) unused parameter 'windowSize' [-Werror,-Wunused-parameter]
```