Fix TFS build of System.Net.WebClient.Tests
Internal builds are failing with:
```
2016-10-21T13:55:07.0700647Z WebClientTest.cs(25,28): error CS7069: Reference to type 'RequestCachePolicy' claims it is defined in 'System.Net.Requests', but it could not be found [D:\A\_work\55\s\corefx\src\System.Net.WebClient\tests\System.Net.WebClient.Tests.csproj]
2016-10-21T13:55:07.0700647Z WebClientTest.cs(269,16): error CS7069: Reference to type 'RequestCachePolicy' claims it is defined in 'System.Net.Requests', but it could not be found [D:\A\_work\55\s\corefx\src\System.Net.WebClient\tests\System.Net.WebClient.Tests.csproj]
2016-10-21T13:55:07.0700647Z WebClientTest.cs(270,31): error CS7069: Reference to type 'RequestCachePolicy' claims it is defined in 'System.Net.Requests', but it could not be found [D:\A\_work\55\s\corefx\src\System.Net.WebClient\tests\System.Net.WebClient.Tests.csproj]
2016-10-21T13:55:08.3669554Z WebClientTest.cs(25,28): error CS7069: Reference to type 'RequestCachePolicy' claims it is defined in 'System.Net.Requests', but it could not be found [D:\A\_work\55\s\corefx\src\System.Net.WebClient\tests\System.Net.WebClient.Tests.csproj]
2016-10-21T13:55:08.3669554Z WebClientTest.cs(269,16): error CS7069: Reference to type 'RequestCachePolicy' claims it is defined in 'System.Net.Requests', but it could not be found [D:\A\_work\55\s\corefx\src\System.Net.WebClient\tests\System.Net.WebClient.Tests.csproj]
2016-10-21T13:55:08.3669554Z WebClientTest.cs(270,31): error CS7069: Reference to type 'RequestCachePolicy' claims it is defined in 'System.Net.Requests', but it could not be found [D:\A\_work\55\s\corefx\src\System.Net.WebClient\tests\System.Net.WebClient.Tests.csproj]
```
Trying to fix it with temporary P2P references.


Commit migrated from https://github.com/dotnet/corefx/commit/ad787293081786e9040aa62ee212c07b1674bc91