Fix debug build of libraries tests
Without this chage there's error:

/home/runtime/src/libraries/System.Net.Security/tests/FunctionalTests/TestConfiguration.cs(29,158): error CS0103: The name 'RuntimeInformation' does not exist in the current context [/home/runtime/src/libraries/System.Net.Security/tests/FunctionalTests/System.Net.Security.Tests.csproj::TargetFramework=net11.0-unix]