AggregateException: Use StringBuilder.AppendFormat (dotnet/coreclrdotnet/corefx#15747)
Use `AppendFormat(...)` instead of `Append(string.Format(...))` and
`AppendLine()` instead of `Append(Environment.NewLine)`.

Signed-off-by: dotnet-bot-corefx-mirror <dotnet-bot@microsoft.com>


Commit migrated from https://github.com/dotnet/corefx/commit/5471a4b90ba5676354b245e2b1f84962dc444f06