Tar: Only treat reparse points marked as junctions or symlinks as actual tar symlinks (#124753)
Fixes https://github.com/dotnet/runtime/issues/82949

Before, we would throw on any reparse point, which is not a
symlink/junction. (because for these, `LinkTarget` is null) and the
exception would be something cryptic like

```
System.ArgumentException: The value cannot be an empty string. (Parameter 'value')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.Formats.Tar.TarEntry.set_LinkName(String value)
```

With this change, we will attempt to include non-symlink reparse points
as regular files,. For some types, where opening the file fails (such as
AppExecLink reparse point), we throw IOException with message that given
file is not supported.

An alternative would be to throw for all non-symlink reparse points
(including file deduplication reparse point mentioned in the original
issue), and only "dereference" these if we implement some sort of
"DereferenceSymlinks" tar creation options.