[runtime] Fixed the iOS build.
Failure caused by https://github.com/mono/mono/commit/mono/mono@2f1b464beb14a1b6b6099a03fc332493293bef35.

```
../../../../../mono/mono/utils/mono-proclib.c:104:8: error: use of undeclared identifier 'errno'
                        if (errno != ENOMEM)
                            ^
../../../../../mono/mono/utils/mono-proclib.c:104:17: error: use of undeclared identifier 'ENOMEM'
                        if (errno != ENOMEM)
```


Commit migrated from https://github.com/mono/mono/commit/20eb41f97a6dcfeb4b738e0efdc9ffc1b9239c05