Unsigned cast for EPOLLHUP bitwise AND `~EPOLLHUP` results in signed int, which makes the compiler throw on `events & ~EPOLLHUP`:
```ash
error: implicit conversion changes signedness: 'int' to 'unsigned int'
      [-Werror,-Wsign-conversion]
```

This change make use of `static_cast<uint32_t>` to satisfy the compiler.


Commit migrated from https://github.com/dotnet/corefx/commit/aa0e901314b0d18222b38f782539ddd37727de22