[tests] InstallWorkloadFromArtifacts: handle a stable band version
If the sdk band version is like `8.0.100` (stable, no with no
preview/ci/dev suffixes), `bandPreleaseVersion`:

`string bandPreleaseVersion = bandVersionRegex().Match(bandVersion).Groups[1].Value;`

.. is `""` which breaks:

` bandVersion = bandVersion.Replace (bandPreleaseVersion, packagePreleaseVersion);`

```
System.ArgumentException: The value cannot be an empty string. (Parameter 'oldValue')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.String.Replace(String oldValue, String newValue)
   at Microsoft.Workload.Build.Tasks.InstallWorkloadFromArtifacts.InstallWorkloadManifest(ITaskItem workloadId, Strin
   at Microsoft.Workload.Build.Tasks.InstallWorkloadFromArtifacts.InstallAllManifests()
   at Microsoft.Workload.Build.Tasks.InstallWorkloadFromArtifacts.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingCo
```

This adds a null/empty string check on the local.