Fix missing RuneLocale on FreeBSD.
Without this patch the build breaks with errors like this:

    /usr/include/xlocale/_ctype.h:52:1: error: unknown type name '_RuneLocale'
    _RuneLocale     *__runes_for_locale(locale_t, int*);
    ^