[wasm] Use latest sdk 7.0 sdk for workload testing, and perf runs (#82219)
Fixes 7.0 perf runs:

```
Traceback (most recent call last):
  File "/mnt/vss/_work/1/s/Payload/performance/scripts/ci_setup.py", line 373, in <module>
    __main(sys.argv[1:])
  File "/mnt/vss/_work/1/s/Payload/performance/scripts/ci_setup.py", line 318, in __main
    dotnet_version = dotnet.get_dotnet_version(target_framework_moniker, args.cli) if args.dotnet_versions == [] else args.dotnet_versions[0]
  File "/mnt/vss/_work/1/s/Payload/performance/scripts/dotnet.py", line 549, in get_dotnet_version
    sdk_path = get_sdk_path(dotnet_path) if sdk_path is None else sdk_path
  File "/mnt/vss/_work/1/s/Payload/performance/scripts/dotnet.py", line 533, in get_sdk_path
    base_path = get_base_path(dotnet_path)
  File "/mnt/vss/_work/1/s/Payload/performance/scripts/dotnet.py", line 527, in get_base_path
    'Did not find "Base Path:" entry on the `dotnet --info` command'
RuntimeError: Did not find "Base Path:" entry on the `dotnet --info` command
```

Co-authored-by: Carlos Sánchez López <1175054+carlossanlop@users.noreply.github.com>