AggregateException: Use StringBuilder.AppendFormat (#15747)
Use `AppendFormat(...)` instead of `Append(string.Format(...))` and
`AppendLine()` instead of `Append(Environment.NewLine)`.