Add System.Threading to packages.config in test projects
This would otherwise make the Mono mcs compiler fail with:
"error CS0518: The predefined type `System.Threading.Interlocked' is defined in an assembly that is not referenced."


Commit migrated from https://github.com/dotnet/corefx/commit/eef738cc609aa18d231dd078d0cf114655c051ce