[runtime] Compile arch before utils when INSTALL_MONOTOUCH is enabled
We'd run into an error before:

```
In file included from ../../mono/utils/mono-context.h:234:0,
                 from ../../mono/utils/mono-stack-unwinding.h:10,
                 from ../../mono/utils/mono-threads.h:14,
                 from mono-mmap.c:36:
../../mono/arch/arm/arm-codegen.h:936:41: fatal error: mono/arch/arm/arm_dpimacros.h: No such file or directory
```

This was done for the other cases in mono/mono@637ee7cbaa03a1f576230eb8601c0c4fa7f93b36, but not when the monotouch
special case was added in mono/mono@cf754cdb634f2bdd5bc959cec66145372c301fba.


Commit migrated from https://github.com/mono/mono/commit/ee0bec4d894d4f2db49111c597d57e4f1bd2bd3e