Turn off -Wcast-align inline for musl-libc
Tracking issue: dotnet/corefx#6312

In musl-libc, CMSG_NXTHDR typecasts char* to cmsghdr* which causes
clang to throw cast-align warning. This change suppresses the warning
inline.

Note, with `-Werror` and `-Weverything`, compiler treats this warning
as the error:

```ash
/root/corefx/src/Native/System.Native/pal_networking.cpp:1311:31: error: cast from 'unsigned char *' to 'struct cmsghdr *'
increases
      required alignment from 1 to 4 [-Werror,-Wcast-align]
             controlMessage = CMSG_NXTHDR(&header, controlMessage))
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/sys/socket.h:267:10: note: expanded from macro 'CMSG_NXTHDR'
        ((struct cmsghdr *)__CMSG_NEXT(cmsg))))
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

musl-libc: https://fossies.org/dox/musl-1.0.5/include_2sys_2socket_8h.html#a4f70853d9633fb80428189cd7bb292d0

[clang/gcc]-libc: http://lxr.free-electrons.com/source/include/linux/socket.h#L89


Commit migrated from https://github.com/dotnet/corefx/commit/ba887267f86cad142981b0837669abfb4f07b210