Don't crossgen existing .ni images
Trying to crossgen existing ni files (e.g. mscorlib.ni.dll) causes
errors to be displayed to the console for example:

```
Error compiling /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/Tools/mscorlib.ni.dll: The process cannot access the file because it is being used by another process.
 (Exception from HRESULT: 0x80070020)
Error: compilation failed for "/mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/Tools/mscorlib.ni.dll" (0x80070020)
Unable to successfully compile /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/Tools/mscorlib.ni.dll
```

Simply skip *.ni.[dll|exe] when crossgening.


Commit migrated from https://github.com/dotnet/corefx/commit/48c9a5b8b110c3564eb927b01946bab849932d35