Add `-s TEXTDECODER=0` to EMCC_FLAGS to work around bug introduced
* Default to TEXTDECODER=2 in -Oz builds to save 0.5KB-1KB of build output size. https://github.com/emscripten-core/emscripten/pull/13304
* Fixes `TextDecoder is not defined` problem with running in console as well as when running the AOT console sample.

```
ReferenceError: TextDecoder is not defined
    at dotnet.js:1:8517
    at loadScript (runtime.js:196:3)
    at runtime.js:280:1

runtime.js:196: Error executing file
                load (url);
```

* Fixes `TextDecoder is not defined` problem when running tests in console.

```
info: ReferenceError: TextDecoder is not defined
  info:     at dotnet.js:1:8517
  info:     at loadScript (runtime.js:196:3)
  info:     at runtime.js:280:1
  info:
  info: runtime.js:196: Error executing file
  info:                 load (url);
  info:   ^
  info:
  info: 09:54:03.1461730 Process v8 exited with 1
```