Fix PALTests build
Something changed in the build or tools that led to build errors like:
```
/__w/1/s/src/coreclr/pal/tests/palsuite/file_io/gettemppatha/test1/gettemppatha.cpp:28:16: error: variable length arrays are a C99 feature [-Werror,-Wvla-extension]
      CHAR  path[dwBufferLength];
                 ^~~~~~~~~~~~~~
```