Workaround compiler warning in test UnixGssFakeNegotiateStream class
Simple change to avoid passing this _context field by ref to suppress the warning:
```
2016-10-22T01:52:17.1092891Z UnixGssFakeNegotiateStream.cs(57,66): error CS0197: Using 'UnixGssFakeNegotiateStream._context' as a ref or out value or taking its address may cause a runtime exception because it is a field of a marshal-by-reference class [D:\A\_work\32\s\corefx\src\System.Net.Security\tests\FunctionalTests\System.Net.Security.Tests.csproj]
```


Commit migrated from https://github.com/dotnet/corefx/commit/f0ffc8c6b518f2761691eb64c76fa6e26239a0f8