Fix method signature for memmove and memset in SpanHelpers.ByteMemOps (#123006)
## Description

This PR fixes modifiers order encountered when building mono runtime.

```
src/libraries/System.Private.CoreLib/src/System/SpanHelpers.ByteMemOps.cs(259,9): error IDE0036: Modifiers are not ordered (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036) [/Users/miloskotlar/dotnet/runtime-ios/src/mono/System.Private.CoreLib/System.Private.CoreLib.csproj]
src/libraries/System.Private.CoreLib/src/System/SpanHelpers.ByteMemOps.cs(482,9): error IDE0036: Modifiers are not ordered (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036) [/Users/miloskotlar/dotnet/runtime-ios/src/mono/System.Private.CoreLib/System.Private.CoreLib.csproj]
```

Introduced in https://github.com/dotnet/runtime/pull/122791