Fix building ReferenceTrackerRuntime.cpp in Interop tests
Building this file on Fedora 38 (with clang 16, libstdc++ 13.1) fails
with an error:

    runtime/src/tests/Interop/COM/ComWrappers/MockReferenceTrackerRuntime/ReferenceTrackerRuntime.cpp:216:49: error: expected ';' after expression
			    throw std::runtime_error{ "Peg failure" };
						    ^
						    ;

    runtime/src/tests/Interop/COM/ComWrappers/MockReferenceTrackerRuntime/ReferenceTrackerRuntime.cpp:216:36: error: no member named 'runtime_error' in namespace 'std'
			    throw std::runtime_error{ "Peg failure" };
				  ~~~~~^

    runtime/src/tests/Interop/COM/ComWrappers/MockReferenceTrackerRuntime/ReferenceTrackerRuntime.cpp:216:64: error: expected ';' after expression
			    throw std::runtime_error{ "Peg failure" };
								   ^
								   ;
    3 errors generated.

The class is defined in <stdexcept>, so import that too.