[cxx] Fix C++ compilation regression. (mono/mono#10702)
Caught by Aleksey Kliger.

transform.c(4251): error C2664: 'MonoReflectionType *mono_type_get_object_checked(MonoDomain *,MonoType *,MonoError *)': cannot convert argument 2 from 'gpointer' to 'MonoType *' [d:\j\workspace\d\msvc\libmono-dynamic.vcxproj]

Cast from void* to non-void*.

Commit migrated from https://github.com/mono/mono/commit/05009a40df8858713f89bbd1646d905b2a5e2445