Fix the return macro on Windows
There seems to be a bug in the VC++ compiler that causes the
following error to occur:
ex.cpp(492): fatal error C1061: compiler limit : blocks nested too deeply
There seems to be no nesting when I look at preprocessed source of the ex.cpp
and it builds fine on Unix.
To make the Windows build happy, I have left the return macro definition
for MSVC as it was before my change and only changed it for other compilers.


Commit migrated from https://github.com/dotnet/coreclr/commit/cf30541e86f27348d9fe132b88d82bda211ab867