Add missing TestLibrary reference for BuildAllTestsAsStandalone=true
This fixes:

error CS0103: The name 'TestLibrary' does not exist in the current context