Avoid memset in case of HENUMInternal (dotnet/coreclr#27690)
gcc9 complains:

```sh
/datadrive/projects/coreclr/src/md/runtime/mdinternalro.cpp: In member function virtual HRESULT MDInternalRO::EnumTypeDefInit(HENUMInternal*):
/datadrive/projects/coreclr/src/md/runtime/mdinternalro.cpp:202:44: error: void* memset(void*, int, size_t) clearing an object of non-trivial type struct HENUMInternal; use assignment or value-initialization instead [-Werror=class-memaccess]
  202 |     memset(phEnum, 0, sizeof(HENUMInternal));
      |                                            ^
In file included from /datadrive/projects/coreclr/src/inc/corpriv.h:21,
                 from /datadrive/projects/coreclr/src/md/runtime/stdafx.h:20,
                 from /datadrive/projects/coreclr/src/md/runtime/mdinternalro.cpp:12:
/datadrive/projects/coreclr/src/inc/metadata.h:87:8: note: struct HENUMInternal declared here
   87 | struct HENUMInternal
      |        ^~~~~~~~~~~~~
```

As it turned out, there already is a static helper defined on this type
with a comment to prefer it over memset, this patch just replaces the
usage.

Commit migrated from https://github.com/dotnet/coreclr/commit/91ee41b6701e1f7f8d3d1fba461a67e240c83c82