Fix missing RuneLocale on FreeBSD.
Without this patch the build breaks with errors like this:

    /usr/include/xlocale/_ctype.h:52:1: error: unknown type name '_RuneLocale'
    _RuneLocale     *__runes_for_locale(locale_t, int*);
    ^


Commit migrated from https://github.com/dotnet/coreclr/commit/3566cf1b958c50a9346269147a7f7ef2bc3919ae