JsonNamingPolicyAttribute: Add missing PascalCase (#135238)
Support for Pascal Case was added in
https://github.com/dotnet/runtime/pull/124644.

However, JsonNamingPolicyAttribute was missed, leading to an exception
when doing something like this:
```csharp
[JsonNamingPolicy(JsonKnownNamingPolicy.PascalCase)]
public class TestClass
{
    public int Property { get; init; }
}
```

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'namingPolicy')
   at System.Text.Json.Serialization.JsonNamingPolicyAttribute.ResolveNamingPolicy(JsonKnownNamingPolicy namingPolicy)
   at System.Text.Json.Serialization.JsonNamingPolicyAttribute..ctor(JsonKnownNamingPolicy namingPolicy)
   at System.Reflection.CustomAttribute.<CreateCustomAttributeInstance>g____PInvoke|30_0(QCallModule __pModule_native, ObjectHandleOnStack __type_native, ObjectHandleOnStack __pCtor_native, IntPtr* __ppBlob_native, IntPtr __pEndBlob_native, Int32* __pcNamedArgs_native, ObjectHandleOnStack __instance_native)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Text.Json.Serialization.Metadata.FSharpCoreReflectionProxy.GetFSharpCoreAssembly(Type type)
   at System.Text.Json.Serialization.Metadata.FSharpCoreReflectionProxy.IsFSharpType(Type type)
   at System.Text.Json.Serialization.Converters.FSharpTypeConverterFactory.CanConvert(Type typeToConvert)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetBuiltInConverter(Type typeToConvert)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetConverterForType(Type typeToConvert, JsonSerializerOptions options, Boolean resolveJsonConverterAttribute)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetTypeInfo(Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfoResolverChain.GetTypeInfo(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoNoCaching(Type type)
   at System.Text.Json.JsonSerializerOptions.CachingContext.CreateCacheEntry(Type type, CachingContext context)
--- End of stack trace from previous location ---
[...]
```

After adding that line, the attribute works as expected.