[wasm] Use test-main.js from 7.0 branch for perf pipeline
Since we use a sdk+workload for running the perf benchmarks, and build
the projects for tfm=net7.0, it uses the 7.0 runtime pack, which has
some differences. So, use the 7.0 test-main.js .

Fails with:

```
[2022/09/11 01:06:47][INFO] test-main.js:262: TypeError: dotnet.withVirtualWorkingDirectory(...).withEnvironmentVariables(...).withDiagnosticTracing(...).withExitOnUnhandledError is not a function
[2022/09/11 01:06:47][INFO]             .withExitOnUnhandledError()
[2022/09/11 01:06:47][INFO]              ^
[2022/09/11 01:06:47][INFO] TypeError: dotnet.withVirtualWorkingDirectory(...).withEnvironmentVariables(...).withDiagnosticTracing(...).withExitOnUnhandledError is not a function
[2022/09/11 01:06:47][INFO]     at run (test-main.js:262:14)
[2022/09/11 01:06:47][INFO]
[2022/09/11 01:06:47][INFO] 1 pending unhandled Promise rejection(s) detected.
```