Squashed commit of the following:
commit 14747dcf058a2129bbbcafacfd8f8adbc47ffef9
Merge: fb9b27c1fb0 118c530033b
Author: Ankit Jain <radical@gmail.com>
Date:   Fri Jun 25 20:48:51 2021 -0400

    Merge remote-tracking branch 'origin/main' into wasm-native-libs-workloads

commit fb9b27c1fb006556d9b71cee6663088c88d17c38
Author: Ankit Jain <radical@gmail.com>
Date:   Fri Jun 25 15:15:26 2021 -0400

    Fix remaining tests

commit 6d43522dbac7768d33b18c4004a7d148d15154df
Merge: 42e42afaedf fc4a42746d9
Author: Ankit Jain <radical@gmail.com>
Date:   Fri Jun 25 12:03:53 2021 -0400

    Merge remote-tracking branch 'origin/main' into wasm-native-libs-workloads

commit 42e42afaedf4c9fb29b93840163f7f6283d030a5
Author: Ankit Jain <radical@gmail.com>
Date:   Fri Jun 25 01:55:52 2021 -0400

    copy nuget.config for blazor test too

commit 4456b1a3dc00e9b5ec7d129c3498d774f789a0d0
Author: Ankit Jain <radical@gmail.com>
Date:   Fri Jun 25 00:33:57 2021 -0400

    fix build

commit ccc2c89c403a7349eb6bb9debccfed4e729e5bb8
Author: Ankit Jain <radical@gmail.com>
Date:   Thu Jun 24 23:33:13 2021 -0400

    Isolate the nuget environment

commit 53adc7d55c700795f3cbabaf64200a319afec525
Author: Ankit Jain <radical@gmail.com>
Date:   Thu Jun 24 20:11:51 2021 -0400

    Bump sdk for workloads to 6.0.100-preview.6.21324.1

commit fbaf2ce408cf53dab2b4db5348e353b037a1a90b
Author: Ankit Jain <radical@gmail.com>
Date:   Thu Jun 24 20:09:30 2021 -0400

    fix tests

commit ba8b922e055547ff9373391a1f215487ed9240a5
Author: Ankit Jain <radical@gmail.com>
Date:   Thu Jun 24 18:50:14 2021 -0400

    skip first time experience

commit a07a59586e8482871fb0ed71877b8853e8e3fb41
Author: Ankit Jain <radical@gmail.com>
Date:   Thu Jun 24 18:47:38 2021 -0400

    fix build error

commit c1487458f7defe608c7a3eaaddc5ea671dc4456d
Author: Ankit Jain <radical@gmail.com>
Date:   Thu Jun 24 18:45:49 2021 -0400

    fix nuget error

commit 5199e9ce862e7fba7dee1d930e81915fbc5a503c
Merge: 0c68049b6ca 1e5ebfed32e
Author: Ankit Jain <radical@gmail.com>
Date:   Thu Jun 24 17:59:13 2021 -0400

    Merge branch 'wasm-native-libs-workloads-pr' into wasm-native-libs-workloads

commit 1e5ebfed32e4c22f6c33a5ad622375c138123d86
Merge: 643c8212d8f c88da290531
Author: Ankit Jain <radical@gmail.com>
Date:   Thu Jun 24 16:49:24 2021 -0400

    Merge remote-tracking branch 'origin/main' into wasm-native-libs-workloads-pr

commit 643c8212d8f2bb45684531d3445e12c75c37839c
Author: Ankit Jain <radical@gmail.com>
Date:   Thu Jun 24 16:49:22 2021 -0400

    fix linux build

commit 9b064d96dc8de5a21afc994c8efc4d7c27d88729
Merge: 5fd632f031a abccfadbf57
Author: Ankit Jain <radical@gmail.com>
Date:   Thu Jun 24 12:20:39 2021 -0400

    Merge remote-tracking branch 'origin/main' into wasm-native-libs-workloads-pr

commit 5fd632f031a854bf36d98a7647c7ef6e15d5ae59
Author: Ankit Jain <radical@gmail.com>
Date:   Thu Jun 24 12:12:18 2021 -0400

    fix casing for runtime pack path

commit b4d48f37bbaa4a899e2444aac47e1d550bbad23b
Author: Ankit Jain <radical@gmail.com>
Date:   Thu Jun 24 02:33:09 2021 -0400

    fix runscript

commit 0c68049b6cac1fabce76af950d6c15c01d9952e1
Author: Ankit Jain <radical@gmail.com>
Date:   Thu Jun 24 02:15:49 2021 -0400

    refactorings

commit 425e2e3c8f84ba1f536a134b70941f939942a1ae
Author: Ankit Jain <radical@gmail.com>
Date:   Thu Jun 24 01:20:16 2021 -0400

    set sdk path for helix

commit 9652f8b82a5e000dadc2e9bf0015ab769d1faae7
Merge: 999de6d4441 dae9156dd0d
Author: Ankit Jain <radical@gmail.com>
Date:   Wed Jun 23 23:46:59 2021 -0400

    Merge remote-tracking branch 'origin/main' into wasm-native-libs-workloads

commit 999de6d44419ca804ffabc719eba02c6b1ed230e
Author: Ankit Jain <radical@gmail.com>
Date:   Wed Jun 23 23:19:42 2021 -0400

    Add missing UsingTask

commit 7636d3823db3f9e6e3223a22ba5ef57e99c6e641
Merge: 2468045aedc 4f3e30e6d34
Author: Ankit Jain <radical@gmail.com>
Date:   Wed Jun 23 22:21:38 2021 -0400

    Merge remote-tracking branch 'origin/main' into wasm-native-libs-workloads

commit 2468045aedcece825bbba39a8163c97bdc796fd7
Merge: 16c83d7d62b f3af8d8b146
Author: Ankit Jain <radical@gmail.com>
Date:   Wed Jun 23 21:23:55 2021 -0400

    Merge remote-tracking branch 'origin/main' into wasm-native-libs-workloads

commit 16c83d7d62b91499a51a81dac63ce8f60ee16d83
Author: Ankit Jain <radical@gmail.com>
Date:   Wed Jun 23 21:23:48 2021 -0400

    Add hack to manually generate sdk.props for the cross compiler

commit 8f9ddfbfced4fbf512df59648fa08df15c2f6bb1
Merge: 57b2950ba4a 0416c3469b7
Author: Ankit Jain <radical@gmail.com>
Date:   Wed Jun 23 12:59:32 2021 -0400

    Merge remote-tracking branch 'origin/main' into wasm-native-libs-workloads

commit 57b2950ba4a10f66d7aedcf497579a5e8c64ae9d
Author: Ankit Jain <radical@gmail.com>
Date:   Tue Jun 22 19:21:51 2021 -0400

    trying to fix the build

commit 63089822f25848d190ab1d8b06468c293e2b9d2a
Author: Ankit Jain <radical@gmail.com>
Date:   Tue Jun 22 15:38:09 2021 -0400

    Don't build Wasm.Build.Tests for linker-tests pipeline

commit 49d5dba9783694a8f57c621e020bfb481ee8971f
Author: Ankit Jain <radical@gmail.com>
Date:   Tue Jun 22 15:34:34 2021 -0400

    Make sure to restore runtime pack project

commit fb4348b38b6061be1a64a2112fed9a8615dbb840
Author: Ankit Jain <radical@gmail.com>
Date:   Tue Jun 22 14:36:50 2021 -0400

    disable Microsoft.NETCore.Platforms.Tests on wasm

    This is already not being sent to CI with `IgnoreForCI=true`.
    It fails on CI with:

    ```
    /_/src/Shared/NativeMethodsShared.cs(855,29): error IL1005: Microsoft.Build.Shared.NativeMethodsShared.SystemInformation.get: Error processing method 'Microsoft.Build.Shared.NativeMethodsShared.SystemInformationData.SystemInformationData()' in assembly 'Microsoft.Build.Utilities.Core.dll' [/__w/1/s/src/libraries/Microsoft.NETCore.Platforms/tests/Microsoft.NETCore.Platforms.Tests.csproj]
    \##[error]/_/src/Shared/NativeMethodsShared.cs(855,29): error IL1005: (NETCORE_ENGINEERING_TELEMETRY=Build) Microsoft.Build.Shared.NativeMethodsShared.SystemInformation.get: Error processing method 'Microsoft.Build.Shared.NativeMethodsShared.SystemInformationData.SystemInformationData()' in assembly 'Microsoft.Build.Utilities.Core.dll'
      Mono.Linker.LinkerFatalErrorException: /_/src/Shared/NativeMethodsShared.cs(855,29): error IL1005: Microsoft.Build.Shared.NativeMethodsShared.SystemInformation.get: Error processing method 'Microsoft.Build.Shared.NativeMethodsShared.SystemInformationData.SystemInformationData()' in assembly 'Microsoft.Build.Utilities.Core.dll'
       ---> System.NotImplementedException: switch
         at Mono.Linker.Steps.UnreachableBlocksOptimizer.BodyReducer.IsConstantBranch(OpCode opCode, Int32 operand) in illink.dll:token 0x6000770+0x41
         at Mono.Linker.Steps.UnreachableBlocksOptimizer.BodyReducer.RemoveConditions() in illink.dll:token 0x6000768+0x22a
         at Mono.Linker.Steps.UnreachableBlocksOptimizer.BodyReducer.RewriteBody() in illink.dll:token 0x6000766+0xa
         at Mono.Linker.Steps.UnreachableBlocksOptimizer.ProcessStack() in illink.dll:token 0x60004e9+0x102
         at Mono.Linker.Steps.UnreachableBlocksOptimizer.ProcessMethod(MethodDefinition method) in illink.dll:token 0x60004e5+0x44
         at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason, Scope& scope) in illink.dll:token 0x600040e+0x9b
         at Mono.Linker.Steps.MarkStep.ProcessQueue() in illink.dll:token 0x6000399+0x24
         --- End of inner exception stack trace ---
         at Mono.Linker.Steps.MarkStep.ProcessQueue() in illink.dll:token 0x6000399+0xaa
         at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue() in illink.dll:token 0x6000396+0xa
         at Mono.Linker.Steps.MarkStep.Process() in illink.dll:token 0x6000393+0x0
         at Mono.Linker.Steps.MarkStep.Process(LinkContext context) in illink.dll:token 0x600038a+0x41
         at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step) in illink.dll:token 0x6000264+0x0
         at Mono.Linker.Pipeline.Process(LinkContext context) in illink.dll:token 0x6000263+0xf
         at Mono.Linker.Driver.Run(ILogger customLogger) in illink.dll:token 0x60000fd+0x20
      Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
    /__w/1/s/.dotnet/sdk/6.0.100-preview.4.21255.9/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(80,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/__w/1/s/src/libraries/Microsoft.NETCore.Platforms/tests/Microsoft.NETCore.Platforms.Tests.csproj]
    \##[error].dotnet/sdk/6.0.100-preview.4.21255.9/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(80,5): error NETSDK1144: (NETCORE_ENGINEERING_TELEMETRY=Build) Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false.
    ```

commit 480373505d9e25c361555d9b0506c70da3287dd5
Author: Ankit Jain <radical@gmail.com>
Date:   Tue Jun 22 14:10:06 2021 -0400

    cleanup

commit 911c54ae28dea7becc7ade908b7ac801bfcc40fa
Merge: f6f8e26b1c6 62b8d02fdbf
Author: Ankit Jain <radical@gmail.com>
Date:   Tue Jun 22 13:26:38 2021 -0400

    Merge remote-tracking branch 'origin/main' into wasm-native-libs-workloads

commit f6f8e26b1c69826a4489482580e9ecaa4b45896b
Author: Ankit Jain <radical@gmail.com>
Date:   Tue Jun 22 13:20:10 2021 -0400

    Directly invoke runtime pack sfxproj, to get the package

commit 998c83d5f6c062ed3e9c16fe1d67c8bddb940d8b
Author: Ankit Jain <radical@gmail.com>
Date:   Tue Jun 22 13:03:12 2021 -0400

    cleanup

commit 81373d93eff8e5ee77984f589434693774624823
Author: Ankit Jain <radical@gmail.com>
Date:   Tue Jun 22 03:27:00 2021 -0400

    Use dotnet6 feed to restore packages

commit c8ca41007128b9ec4723486bee504afc69ac3343
Author: Ankit Jain <radical@gmail.com>
Date:   Tue Jun 22 02:58:02 2021 -0400

    get the version from envvar

commit c66de8622cb4566ff883f6c84cadf0f9bb1a0a7e
Author: Ankit Jain <radical@gmail.com>
Date:   Sun Jun 20 18:00:04 2021 -0400

    Fix to use the correct ref pack

commit 4554f301941f56731da352393cc525c0c607a69a
Author: Ankit Jain <radical@gmail.com>
Date:   Sun Jun 20 17:10:04 2021 -0400

    fixes

commit 8f01a0aebe32aa8376be37d61bf10f0a443faac1
Author: Ankit Jain <radical@gmail.com>
Date:   Sun Jun 20 15:54:51 2021 -0400

    fix tests

commit 99e84734dd415abb3117584c60f2e3c0d5cf4852
Author: Ankit Jain <radical@gmail.com>
Date:   Sun Jun 20 14:41:49 2021 -0400

    this seems to get the runtime pack building

commit 967d60e06d3206eec83752cea5bb8f0d79961bf4
Author: Ankit Jain <radical@gmail.com>
Date:   Sun Jun 20 11:42:48 2021 -0400

    fix build

commit 3c1ef3355cf0ec57c16534d52200e31fa5d6fdf6
Author: Ankit Jain <radical@gmail.com>
Date:   Sun Jun 20 11:24:44 2021 -0400

    fix DirectoryCopy

commit a20102c574528a6835598958730e9c26e655e533
Author: Ankit Jain <radical@gmail.com>
Date:   Sun Jun 20 08:57:13 2021 -0400

    fix net6.0 test builds

commit 2fa559ec0ed5822834a7c9b0f905e496a4c7c5db
Author: Ankit Jain <radical@gmail.com>
Date:   Sun Jun 20 08:18:21 2021 -0400

    cleanup

commit 0ffd96cf7d1dbff748512b8d1d3b6548233b2b4e
Author: Ankit Jain <radical@gmail.com>
Date:   Sun Jun 20 04:23:21 2021 -0400

    debug

commit 8e754bf7650f2ab83d1a45a5e096d8fcaf080fc4
Author: Ankit Jain <radical@gmail.com>
Date:   Sun Jun 20 03:16:33 2021 -0400

    fix build, move doesn't work on CI - invalid cross-device link

commit 53ec67103d90e3cfda73b5423b6a416b67a58b88
Author: Ankit Jain <radical@gmail.com>
Date:   Sun Jun 20 02:12:39 2021 -0400

    undo changes to wasm samples

commit 1fe8601850289bf97a1ede3415276773e6eec079
Author: Ankit Jain <radical@gmail.com>
Date:   Sun Jun 20 02:11:52 2021 -0400

    cleanup

commit 529fb8698165376b6246448ff5be76e6fe4adf54
Author: Eric StJohn <ericstj@microsoft.com>
Date:   Sat Jun 19 13:31:12 2021 -0700

    Remove System.Security.Cryptography.Cng from ASP.NET transport package (#54428)

commit 04e7a11ecd7eb1826d14634d7c08bff4665b17e9
Author: Bruce Forstall <brucefo@microsoft.com>
Date:   Sat Jun 19 10:07:59 2021 -0700

    Disable tests for #54007 (#54207)

commit d0798cd272bb71194a21350da1f10e624bb62fbd
Author: Ankit Jain <radical@gmail.com>
Date:   Sun Jun 20 00:40:56 2021 -0400

    fix running dotnet-install.sh on linux

commit fe05df865629e14b92af6af4233a59ae9ac935cf
Author: Ankit Jain <radical@gmail.com>
Date:   Sat Jun 19 22:46:55 2021 -0400

    fix helix build

commit 3a224d38593e5e60334ff2d1debe26ff395506e8
Author: Ankit Jain <radical@gmail.com>
Date:   Sat Jun 19 09:03:16 2021 -0400

    try helix

commit 5c5212479503aeaef3d7335e5c011e5548f758b5
Author: Ankit Jain <radical@gmail.com>
Date:   Sat Jun 19 05:55:09 2021 -0400

    fix order of args to emcc

commit 84750efbaf73a84596700832c699ddfea73573da
Author: Ankit Jain <radical@gmail.com>
Date:   Sat Jun 19 05:30:35 2021 -0400

    fixed

commit 4e0318f09eaac0113da8a5c82634ef8997b43a46
Author: Ankit Jain <radical@gmail.com>
Date:   Sat Jun 19 04:08:18 2021 -0400

    add BuildEnvironment.cs

commit 0b8766423fc677f44c0580fe21f812d7ff6e9cd4
Author: Ankit Jain <radical@gmail.com>
Date:   Sat Jun 19 02:58:09 2021 -0400

    remove native-libs sample

commit 55cbd78aa21dab49f3daab53a89b092cd05e3761
Author: Ankit Jain <radical@gmail.com>
Date:   Sat Jun 19 02:28:04 2021 -0400

    [wip] wasm native libs, and testing wbt with workloads

Run wasm.build.tests with, and without workloads

cleanup

remove old copy of test

wip

Fix helix job for non-workload run

umm.. wip.. till previous commit, it works on helix..

try to fix non-workloads test run

cleanup, and fix windows command line

cleanup

Remove redundant functional tests

build samples in parallel

Revert Utils.DirectoryCopy, and creat dirs wher needed

fix windows build

fix build

fix dir copy

don't build samples, and functional tests on eat, aot lanes

cleanup

Test with latest sdk (6.0.100-preview.7.21326.4)

rename runscript

trying on windows

add test for checking UnixFilePermissions.xml in the packs

cleanup

cleanup