[libs] Include pthread.h where pthread_once is used
pal_hmac.c uses pthread_once_t and PTHREAD_ONCE_INIT but includes neither
pthread.h nor anything that is guaranteed to pull it in - it relied on the
OpenSSL headers doing so. OpenSSL 3.5 no longer does, and the file stops
compiling:

    error: use of undeclared identifier 'PTHREAD_ONCE_INIT'
    error: call to undeclared function 'pthread_once'

Include it directly, as pal_evp.c, opensslshim.c and pal_bio.c in the same
library already do.

Signed-off-by: Maxim Menshikov <maksim.menshikov@nethermind.io>