Rename Crossgen2 dependency graph ETW event source
When crossgen2 is run with `Microsoft-ILCompiler-Perf` provider enabled, events are not named properly in PerfView (`Microsoft-ILCompiler-Perf/EventID(1)` instead of `Compilation/Start`) and an error event indicating multiple EventSource instances with the same GUID are enabled:
```
    ERROR: Exception in Command Processing for EventSource Microsoft-ILCompiler-Perf: An instance of EventSource with Guid 607164a4-cacb-5f22-92fb-62a11541e285 already exists.
```

Name the dependency analysis EventSource `Microsoft-ILCompiler-Graph-Perf` to distinguish between the two.