Revert "address review feedback"
This reverts commit 4975dc35664e4f3b11a91a689d65b3b3564b915d.

This caused library aot tests to fail with:
```
info: MONO_WASM: mono_wasm_load_runtime () failed TypeError: t.getWasmIndirectFunctionTable is not a function
info: MONO_WASM: TypeError: t.getWasmIndirectFunctionTable is not a function
info:     at Ma (/root/helix/work/workitem/e/wasm_build/AppBundle/_framework/dotnet.runtime.js:3:80285)
info:     at Ul (/root/helix/work/workitem/e/wasm_build/AppBundle/_framework/dotnet.runtime.js:3:174663)
info:     at do_jit_call (do_jit_call (wasm://wasm/0dec238a:wasm-function[90022]:0x16bba99))
info:     at mono_interp_exec_method (mono_interp_exec_method (wasm://wasm/0dec238a:wasm-function[90012]:0x16af791))
info:     at interp_runtime_invoke (interp_runtime_invoke (wasm://wasm/0dec238a:wasm-function[90052]:0x16bc9da))
info:     at mono_jit_runtime_invoke (mono_jit_runtime_invoke (wasm://wasm/0dec238a:wasm-function[95289]:0x17c5028))
info:     at do_runtime_invoke (do_runtime_invoke (wasm://wasm/0dec238a:wasm-function[94085]:0x178e3d3))
info:     at mono_runtime_invoke_checked (mono_runtime_invoke_checked (wasm://wasm/0dec238a:wasm-function[94084]:0x178e38f))
info:     at mono_runtime_install_appctx_properties (mono_runtime_install_appctx_properties (wasm://wasm/0dec238a:wasm-function[91526]:0x17054e4))
info:     at mono_runtime_init_checked (mono_runtime_init_checked (wasm://wasm/0dec238a:wasm-function[91521]:0x1704d4e))
info:     at mini_init (mini_init (wasm://wasm/0dec238a:wasm-function[95272]:0x17c43ea))
info:     at mono_jit_init_version (mono_jit_init_version (wasm://wasm/0dec238a:wasm-function[95408]:0x17ca553))
info:     at mono_wasm_load_runtime (mono_wasm_load_runtime (wasm://wasm/0dec238a:wasm-function[103299]:0x1900987))
info:     at Module._mono_wasm_load_runtime (/root/helix/work/workitem/e/wasm_build/AppBundle/_framework/dotnet.native.js:6817:114)
info:     at ccall (/root/helix/work/workitem/e/wasm_build/AppBundle/_framework/dotnet.native.js:5851:22)
info:     at Object.mono_wasm_load_runtime (/root/helix/work/workitem/e/wasm_build/AppBundle/_framework/dotnet.native.js:5877:16)
info:     at Dl (/root/helix/work/workitem/e/wasm_build/AppBundle/_framework/dotnet.runtime.js:3:215804)
info:     at /root/helix/work/workitem/e/wasm_build/AppBundle/_framework/dotnet.runtime.js:3:205340
info:     at /root/helix/work/workitem/e/wasm_build/AppBundle/_framework/dotnet.runtime.js:3:206020
```