Fix missing TestLibrary for BuildAllTestsAsStandalone=true
This fixes:

error CS0103: The name 'TestLibrary' does not exist in the current context [/home/runtime/src/tests/JIT/Directed/VectorABI/VectorMgdMgd_r.csproj]