Disable failing outerloop tests and fix a build issue in MonoAOTCompiler
See https://github.com/dotnet/runtime/issues/89921 for the test failures.

Additionally, the Android build was failing while compiling an AOT test due to this error:

```
/__w/1/s/artifacts/bin/Android.Device_Emulator.Aot.Test/Release/net8.0/android-x64/AppBundle/modules.c:51:6: error: no previous prototype for function 'register_aot_modules' [-Werror,-Wmissing-prototypes]
void register_aot_modules ()
     ^
```

This is because we turned on `-Werror=missing-prototypes` in https://github.com/dotnet/runtime/pull/89197 but the MonoAOTCompiler didn't emit a function prototype in modules.c

Fixes https://github.com/dotnet/runtime/issues/89566