tasks: Fix sourcebuild for WorkloadBuildTasks
`WorkloadBuildTasks` project uses source generated regex, which requires
the corresponding analyzer to be used. But for net8.0, in source build
the prebuilt package does not have the analyzers which causes the build
to fail like:

`/__w/1/s/artifacts/sb/src/src/tasks/WorkloadBuildTasks/InstallWorkloadFromArtifacts.cs(61,38): error CS8795: Partial method 'InstallWorkloadFromArtifacts.bandVersionRegex()' must have an implementation part because it has accessibility modifiers. [/__w/1/s/artifacts/sb/src/src/tasks/WorkloadBuildTasks/WorkloadBuildTasks.csproj::TargetFramework=net8.0]`

Since the net8.0 build for the task is needed only for the internal
nuget being produced, we can skip the net8.0 build for source builds.

Also, build WorkloadTest.Internal nuget only when building wasm