[System.Runtime.Loader] Add hot reload test infrastructure  (#51144)
Adding infrastructure for hot reload testing.

For each test we define a new library assembly project.  The `.csproj` has a `DeltaScript` property that specifies a JSON file that lists the name of an initial source file, and a list of updated versions of that file.  The https://github.com/dotnet/hotreload-utils Microsoft.DotNet.HotReload.Utils.Generator.BuildTool nuget .targets file will run a generator tool during the build to read the delta script and creates metadata, IL and PDB deltas that incorporate the updates.

The main testsuite references all the test assemblies, and when a test runs, it calls `ApplyUpdateUtil.ApplyUpdate` to load subsequent deltas and then compares the results before and after an update.

Dependencies:

- https://github.com/dotnet/hotreload-utils  - there is now a `Microsoft.DotNet.HotReload.Utils.Generator.BuildTool` MSBuild targets nupkg on the `dotnet6-transport` nuget feed.
- If `DOTNET_MODIFIABLE_ASSEMBLIES` is not set in the environment, we use remote executor to run the tests.

Mono is technically enabled, but practically it's not running anywhere:
- We have not enabled the MonoMetadataUpdate feature support on desktop linux or macos
- For wasm, ios and Android since we don't have remote executor support, we would need to adjust the test pipelines to pass the `DOTNET_MODIFIABLE_ASSEMBLIES` flag via xharness (and the app builder tasks).
- For ios and Android we would need to enable the interpreter as the execution engine, otherwise the tests are skipped.

To try it out locally with CoreCLR run:

```
./dotnet.sh build src/libraries/System.Runtime.Loader/tests /t:Test
```

For mono, build the runtime with `/p:MonoMetadataUpdate=true` and setenv `MONO_ENV_OPTIONS=--interp`

---


* [System.Runtime.Loader] Add hot reload test infrastructure

   Adding infrastructure for hot reload testing.

* Make a proper task for computing hotreload-delta-gen output files

* Don't need DeltaCount property, compute from json

   Compute the number of deltas that hotreload-delta-gen will produce by parsing the json script and counting the number of changes.

* Add dependency on hotreload-delta-gen tool

* use 'dotnet tool run hotreload-delta-gen' to generate EnC deltas

* Use remote executor if DOTNET_MODIFIABLE_ASSEMBLIES is not set

* Use DotNetTool property to run hotreload-delta-gen

   just `dotnet tool run hotreload-delta-gen` can fail on 6.0 preview 2 because of borked argument parsing

* Don't run on Mono for now

   1. mobile devices and wasm will need xharness or the app builder tasks to set the DOTNET_MODIFIABLE_ASSEMBLIES environment variable.
   2. for console apps, we need the hot reload capabilities API to check if the current runtime can do updates

* bump hotreload-delta-gen package version

* Run tests on Mono if feature enabled and interp is used

* fix remote executor detection

   just calling RemoteExecutor.IsSupported on wasm throws

   ```
   System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.RemoteExecutor.RemoteExecutor' threw 
an exception.
   ---> System.PlatformNotSupportedException: System.Diagnostics.Process is not supported on this platform.
   ```

* remove unneeded DefineConstants

* Use `$(TargetPath)` as input to ComputeDeltaOutputNames

   Co-authored-by: Viktor Hofer <viktor.hofer@microsoft.com>

* drop "BuildingProject" property check

   It's for the old project style, only

* Use Microsoft.DotNet.HotReload.Utils.Generator.BuildTool instead of hotreload-delta-gen

   Use an msbuild target nuget instead of the CLI tool

* Use well known version for Generator BuiltTool version

* Use published Generator.BuildTool package

* fix typos, indentantion; add copyright headers

* Remove ComputeDeltaFileOutputNames use nuget version

   The Microsoft.DotNet.HotReload.Utils.Generator.BuildTool nuget now includes a task to compute the output names.  So the targets in the nuget are entirely self-contained now - incremental builds and project references should work now.

   Bump to version 1.0.1 of Generator.BuildTool which has the necessary targets

* Fix style nits; add more copyright headers

Co-authored-by: Viktor Hofer <viktor.hofer@microsoft.com>