[s390x] add in-process crash reporter for s390x (#131796)
Fixes #131535 for linux-s390x, #131604 introduced a build error

```
  /home/sanjam/runtime/src/coreclr/debug/crashreport/inproccrashreporter.cpp:62:2: error: "Unsupported arch"
     62 | #error "Unsupported arch"
        |  ^
  /home/sanjam/runtime/src/coreclr/debug/crashreport/inproccrashreporter.cpp:89:1: error: expected expression
     89 | struct StackOverflowTraceFrame
        | ^
  /home/sanjam/runtime/src/coreclr/debug/crashreport/inproccrashreporter.cpp:102:5: error: unknown type name 'StackOverflowTraceFrame'; did you mean 'StackOverflowTraceSnapshot'?
    102 |     StackOverflowTraceFrame frames[CRASHREPORT_STACK_OVERFLOW_MAX_TRACE_FRAMES];
        |     ^~~~~~~~~~~~~~~~~~~~~~~
        |     StackOverflowTraceSnapshot


....

  /home/sanjam/runtime/src/coreclr/debug/crashreport/inproccrashreporter.cpp:1245:6: error: "Unsupported arch"
   1245 |     #error "Unsupported arch"
        |      ^
  /home/sanjam/runtime/src/coreclr/debug/crashreport/inproccrashreporter.cpp:1258:12: error: use of undeclared identifier 'CRASH_MCREG_PC'
   1258 |     return CRASH_MCREG_PC(ucontext);
        |            ^
  /home/sanjam/runtime/src/coreclr/debug/crashreport/inproccrashreporter.cpp:1271:12: error: use of undeclared identifier 'CRASH_MCREG_SP'
   1271 |     return CRASH_MCREG_SP(ucontext);
        |            ^
  /home/sanjam/runtime/src/coreclr/debug/crashreport/inproccrashreporter.cpp:1284:12: error: use of undeclared identifier 'CRASH_MCREG_FP'
   1284 |     return CRASH_MCREG_FP(ucontext);
```

---------

Co-authored-by: Adeel Mujahid <3840695+am11@users.noreply.github.com>