Disable warning 1685 (aka multiple predefine types) because some versions of csc are picker then others about whether or not they give this warning (which turns into errors and build breaks).
Example of what was being hit:
error CS1685: The predefined type 'Task<TResult>' is defined in multiple assemblies in the global alias; using definition from 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'

The core of the problem is because we are referencing mscorlib and contracts in the default build, which is sometimes trouble because of duplicate type definitions.

[tfs-changeset: 1607022]


Commit migrated from https://github.com/dotnet/corefx/commit/474adf7a53872934ead151f34709b764e7f136b7