Fix x86chk build break:
ndp\clr\src\debug\ee\debugger.h(1117): error C2220: warning treated as error - no 'object' file generated
ndp\clr\src\debug\ee\debugger.h(1117): warning C4324: 'DebuggerHeapExecutableMemoryChunk' : structure was padded due to __declspec(align())

[tfs-changeset: 1565087]


Commit migrated from https://github.com/dotnet/coreclr/commit/6a659231603205bfc24e4428f1edd003c786613f