Gnuport cleanup 3 (dotnet/coreclr#22581)
* Reorder extern "C" and visibility statements

In file included from coreclr/src/pal/inc/pal.h:70:0,
coreclr/src/pal/inc/pal_mstypes.h:30:25: error: expected unqualified-id
before string constant
 #define EXTERN_C extern "C"
                          ^
coreclr/src/pal/inc/rt/palrt.h:216:30: note:
  in expansion of macro 'EXTERN_C'
   #define STDAPI_(type)        EXTERN_C type STDAPICALLTYPE

* Need double quotes around single quotes in error statements

fix error statements

Can't have ' character in error statement

* Abstract __declspec(noinline)

Generate compiler independent macros for noinline request.

* Remove unused DBG_NOINLINE_X86__RET_INLINE

* Abstract __declspec(nothrow)


Commit migrated from https://github.com/dotnet/coreclr/commit/36931ac7b24249201547f7ca667105014b2e4c7f