Disable SslStreamAlertTests by making them netcoreapp1.1 specific
After https://github.com/dotnet/corefx/pull/11489

This error shows up after trying to consume the new packages.
 SslStreamAlertsTest.cs(81,30): error CS1061: 'SslStream' does not contain a definition for 'ShutdownAsync' and no extension method 'ShutdownAsync' accepting a first argument of type 'SslStream' could be found (are you missing a using directive or an assembly reference?) [D:\A\_work\55\s\corefx\src\System.Net.Security\tests\FunctionalTests\System.Net.Security.Tests.csproj]

For now disabling these tests by conditioning them on netcoreapp1.1.


Commit migrated from https://github.com/dotnet/corefx/commit/4f9f7365aa655f8261d3200e6ddeac8607032d91