[MonoDroid] Fix the libmono build.
7e49d08a nee 2763aae9c doesn't build because <fcntl.h> is missing:

	mono/utils/mono-proclib.c:517: error: 'O_RDONLY' undeclared (first use in this function

Fix the build.


Commit migrated from https://github.com/mono/mono/commit/f2f9d7933b87f398f45e42bda2426141d64a5416