Don't bind against non-shipping contract assemblies
Manual backport of c8503d39053f9e0d94716a23c406b66f126ca259
Fixes https://github.com/dotnet/runtime/issues/77988
Unblocks https://github.com/dotnet/runtime/pull/78532

Introduce the AnnotateTargetPathWithContract switch to
make it configure-able when a source project should
return the reference project's assembly instead of
the source assembly, when other projects compile
against it. Set it so that reference assemblies are
only returned for NetCoreAppCurrent tfms or when the
project isn't packable.

- Fix System.DirectoryServices.AccountManagement build
System.DirectoryServices.AccountManagement now builds against
src/System.DirectoryServices instead of ref/System.DirectoryServices
(because the package doesn't contain the ref assembly).

Because of that, the compiler now gets confused because of the
System.DirectoryServices.Interop namespace and the global Interop class.
This happens even though the DirectoryServices.Interop namespace doesn't include any
public types.

That results in the following errors:

src\libraries\System.DirectoryServices.AccountManagement\src\System\DirectoryServices\AccountManagement\AD\SidList.cs(50,26): error CS0246: The type or namespace name 'SID_AND_ATTRIBUTES' could not be found (are you missing a using directive or an assembly reference?)
src\libraries\System.DirectoryServices.AccountManagement\src\System\DirectoryServices\AccountManagement\interopt.cs(439,20): error CS0246: The type or namespace name 'UNICODE_INTPTR_STRING' could not be found (are you missing a using directive or an assembly reference?)
This commit fixes that by removing the System.DirectoryServices.Interop
namespace and moving the types into the parent namespace.

- Suppress nullable warnings in Serialization.Schema
Now that Schema compiles against the source assembly of System.CodeDom,
it receives nullability errors. I'm suppressing them manually for now
but am filing an issue to correctly fix those.

Related: https://github.com/dotnet/runtime/issues/78036