[cxx] Remove two excess toplevel consts in structs, one a C++ problem, one very obscure/hypothetical. (mono/mono#9955)
* [cxx] mono-merp.c:83:9: error: implicit default constructor for 'MERPStruct' must explicitly initialize the const member 'systemModel'

There are possible other solutions involving initializing up front, and later casting away const for additional initialization. Having public-const private-mutable is a good-seeming interface, but is pretty rare. Maybe in [cxx]future can restore const, add a constructor,  etc.

* Remove toplevel const in struct for extremely obscure reasons, again pretty rare pattern.

The obscure reason:

given:
```
typedef struct foo
{
  const int i; // remove const to fix
} foo;

foo global = { 1 };
```
compiled as C++, with some recent versions of Visual C++, there is a regression
where it thinks this is a dynamic initialization. Which is usually ok, but can be a problem in unusual cases (true story..delayload implementation..).


Commit migrated from https://github.com/mono/mono/commit/64d7a6e57ae96059538c4fb6f18e59c616718bdf